#cloud-config
users:
  - name: litwein
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwhxCpMeazwHsPu1xsJI4M3hmN/RW2iS3TfRilDsWC4 yc-hw

package_update: true
package_upgrade: false

runcmd:
  - export HOME=/root && curl -fsSL https://code-server.dev/install.sh | sh
  - mkdir -p /home/litwein/.config/code-server
  - |
    cat > /home/litwein/.config/code-server/config.yaml <<'EOF'
    bind-addr: 0.0.0.0:8080
    auth: password
    password: fydx8353
    cert: false
    EOF
  - chown -R litwein:litwein /home/litwein/.config
  - systemctl enable --now code-server@litwein
